# Generated by Django 5.2.2 on 2025-06-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('setor', models.CharField(max_length=100)),
                ('prioridade', models.CharField(choices=[('MEDIA', 'Media'), ('BAIXA', 'Baixa'), ('ALTA', 'Alta')])),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('PRONTO', 'Pronto'), ('FAZENDO', 'Fazendo')], default='A Fazer')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saep.usuario')),
            ],
        ),
    ]
